---
title: "Analysis"
author: "Yuka, Adela, Jack"
date: "`r Sys.Date()`"
output: html_document
---
## loading library
```{r}
library(tidyverse)
library(broom)
```

```{r}
NBA <- read_csv("data/NBA.csv")
colnames(NBA)

salarymodel <- NBA %>% 
  select(-rk, -player, -player_id, -`17_18salary`, -name, -tm, -`fg`, -`fga`, -`3p`, -`3pa`, -`2p`, -`2pa`, -pos, -ft, -fta, -g, -gs)
```
Data exploratory analysis
```{r}
library(GGally)
salarymodel %>%
    ggpairs()
```

```{r}
lmmodel <- lm(`16_17_salary` ~ ., data = salarymodel)
mult_sal <- tidy(lmmodel)
mult_sal
```
```{r}
g_mult_sal <- broom::glance(lmmodel)
g_mult_sal
```
```{r}
library(lbutils)
full_anova <- lb_anovat_lm(lmmodel, reg_collapse = TRUE)
full_anova

```

```{r}
library(GGally)
salarymodel %>%
    ggpairs()
```

```{r}
qplot(data = salarymodel, x = `16_17_salary`, geom = "histogram", main = "Distribution of 2016-2017 Salary", bins = 20, color = I("black"), fill = I("blue"))
```

```{r}
qplot(data = salarymodel, y = `16_17_salary`, geom = "boxplot", main = "Distribution of 2016-2017 Salary")

```

```{r}
salarymodel %>%
  mutate(lnsalary = log(`16_17_salary`)) -> salarymodel

qplot(data = salarymodel, x = lnsalary, geom = "histogram", bins = 20, color = I("black"), fill = I("blue"), main = "Distribution of ln(2016-2017 Salary)")
```
```{r}
qplot(data = salarymodel, y = lnwages, geom = "boxplot", main = "Distribution of ln(salary)")

```

```{r}
ggplot(data = salarymodel, aes(sample = lnsalary)) +
  stat_qq() +
  stat_qq_line(color = I("blue"))
```

```{r}
simpleage <- lm(data = salarymodel, lnsalary ~ age)
tidy(simpleage)
```

```{r}
glance(simpleage)

```

```{r}
res_age <- augment(simpleage)
```

```{r}
ggplot(data = salarymodel, aes(x = age, y = lnsalary)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```
```{r}
qplot(data = res_age, x = .fitted, y = .resid, geom = "point", main = "Residuals vs Fitted Values for Regressing lnsalary on age")
```

```{r}
salarymodel %>%
  mutate(agesq = age*age) ->
  salarymodel

quadmod <- lm(lnsalary ~ age + agesq, data = salarymodel)
tidy(quadmod)
```

```{r}
glance(quadmod)
```

```{r}
res_quadmod <- augment(quadmod, data = salarymodel)
```

```{r}
ggplot(data = res_quadmod) +
  geom_point(aes(x = age, y = lnsalary)) +
  geom_line(aes(x =age, y = .fitted, color = I("blue")))

```

