---
title: "Data Cleaning & Tidying"
author: "Group 4 Yuka Chen, Jack Lo, Adela Yang""
date: "`r Sys.Date()`"
output: html_document
---
```{r}
## loading data
library(tidyverse)
library(broom)
```

```{r}
# setwd(STAT615NBA/data)
performance16_17 <- read_csv("player16_17.csv")

performance16_17 %>% 
  filter(Tm != "TOT") -> performance16_17
```

```{r}
team_name <- read_csv("team_names.csv") 

team_name%>% 
  mutate(prefix_1 = str_to_upper(prefix_1)) -> team_name

performance16_17 %>% 
  left_join(team_name, by = c("Tm" = "prefix_1")) -> performance16_17
```

```{r}
names(performance16_17)[1:31] <- tolower(names(performance16_17)[1:31])
glimpse(performance16_17)
```


```{r}
salaries_record <- read_csv("salaries_1985to2018.csv")
```


```{r}
## performance for 2016 to 2017
old_salary <- salaries_record %>%   
  filter(season_start == 2016) %>% 
  rename("16_17_salary" = salary)

NBAinfo <- performance16_17 %>% 
  left_join(old_salary, by = c("player_id" = "player_id", "name" = "team")) %>% 
  drop_na()

NBAinfo %>% 
  dplyr::select(-season,-prefix_2,-league,-season_end,-season_start) -> NBAinfo
```


### 2017~2018 - 2016~2017 salaries
```{r}

new_salary <- salaries_record %>% 
  filter(season_start == 2017) %>% 
  rename("17_18salary" = salary) #new_name = old_name


NBAinfo <- NBAinfo %>% 
    left_join(new_salary, by = c("player_id" = "player_id", "name" = "team"))

  NBAinfo %>% 
   dplyr::select(-league,-season_end,-season_start, -season) -> NBAinfo 
  
write_csv(NBAinfo, "NBA.csv")
  
```

### data frame we will use to analyze
```{r}
NBA <- NBAinfo %>% 
  semi_join(new_salary, by = "player_id")

colnames(NBA)
#tm TOT means total, some players played for multiple teams
```

