---
title: "Data Cleaning & Tidying"
author: "Group 4 Yuka Chen, Jack Lo, Adela Yang""
date: "`r Sys.Date()`"
output: html_document
---
```{r}
## loading data
library(tidyverse)
library(broom)
```

```{r}

# setwd(STAT615NBA/data)
performance16_17 <- read_csv("player16_17.csv")
names(performance16_17)[1:31] <- tolower(names(performance16_17)[1:31])
glimpse(performance16_17)
```


```{r}
salaries_record <- read_csv("salaries_1985to2018.csv")
```


```{r}
## performance for 2016 to 2017
old_salary <- salaries_record %>%   
  filter(season_start == 2016) %>% 
  rename("old_salary" = salary)

NBAinfo <- performance16_17 %>% 
    inner_join(old_salary, by = "player_id")
```


### 2017~2018 - 2016~2017 salaries
```{r}
<<<<<<< HEAD
new_salary <- salaries_record %>% 
  filter(season_start == 2017) %>% 
  rename( "new_salary" = salary) %>% #new_name = old_name
  select(player_id, new_salary)
=======
new_salary <- salaries_record %>%  
  select(player_id, season_start, team, salary) %>% 
  filter(season_start == "2017"| season_start == "2016") %>% 
  spread(key = "season_start", value = "salary")


NBAinfo <- performance16_17 %>% 
    inner_join(new_salary, by = "player_id")
>>>>>>> 227f95417563b50dff119465a8618fd9b870188e
```

### data frame we will use to analyze
```{r}
NBA <- NBAinfo %>% 
  left_join(new_salary, by = "player_id") %>% 
  select(-league, -season_start, -season_end, -season, -team, -rk, -player_id) %>% 
    distinct(player, tm, .keep_all = TRUE) 

colnames(NBA)
#tm TOT means total, some players played for multiple teams
```

hellooooooo